<?php
echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Login</title><link rel="stylesheet" href="styles.css">';
echo '<style>'; 
echo 'body{margin:0;font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial}';
echo '.login-wrap{display:grid;grid-template-columns:1fr 1fr;min-height:100vh}';
echo '.left{display:flex;align-items:center;justify-content:center;padding:40px}';
echo '.right{background:#ede9fe;display:flex;align-items:center;justify-content:center}';
echo '.card{max-width:420px;width:100%}';
echo '.brand{font-weight:600;margin-bottom:24px;font-size:20px}';
echo 'h2{margin:0 0 8px 0;font-size:28px}';
echo 'p.muted{color:#6b7280;margin:0 0 16px 0}';
echo 'label{display:block;margin:10px 0 6px 0;color:#374151}';
echo 'input[type=email],input[type=password]{width:100%;padding:10px 12px;border:1px solid #d1d5db;border-radius:8px}';
echo '.row{display:flex;align-items:center;justify-content:space-between;margin:12px 0}';
echo '.btn.primary{background:#6d28d9;color:#fff;border:none;border-radius:8px;padding:10px 14px;width:100%;cursor:pointer}';
echo '.btn.google{margin-top:10px;background:#fff;border:1px solid #d1d5db;color:#111827;border-radius:8px;padding:10px 14px;width:100%;cursor:pointer}';
echo '.actions{display:flex;justify-content:space-between;margin-top:8px}';
echo '.link{color:#6d28d9;text-decoration:none}';
echo '.illustration{max-width:520px;width:100%;}';
echo '@media(max-width:900px){.login-wrap{grid-template-columns:1fr}.right{display:none}}';
echo '</style>';
echo '</head><body>'; 
echo '<div class="login-wrap">';
echo '<div class="left">';
echo '<div class="card">';
echo '<div class="brand">Dailygoods</div>';
echo '<h2>Welcome back</h2>';
echo '<p class="muted">Please enter your details</p>';
echo '<form method="post" action="actions/login.php">';
echo '<label>Email address</label><input type="email" name="email" placeholder="you@gmail.com" required />';
echo '<label>Password</label><input type="password" name="password" required />';
echo '<div class="row">';
echo '<div><input type="checkbox" id="remember" name="remember" value="1" /> <label for="remember" style="display:inline;color:#374151">Remember for 30 days</label></div>';
echo '<div><a class="link" href="#">Forgot password</a></div>';
echo '</div>';
echo '<button class="btn primary" type="submit">Sign in</button>';
echo '<button class="btn google" type="button" onclick="alert(\'Google sign-in coming soon\')">Sign in with Google</button>';
echo '</form>';
echo '<div class="actions"><span>Don\'t have an account?</span> <a class="link" href="index.php?page=register">Sign up</a></div>';
echo '</div>';
echo '</div>';
echo '<div class="right">';
echo '<img class="illustration" src="assets/images/cow.png" alt="Fresh Milk" />';
echo '</div>';
echo '</div>';
echo '</body></html>';
?>